version: '3.6'
services:
  db:
    image: postgres
    container_name: shoppingList_local
    ports:
      - "5435:5432"
    environment:
      #reffered from spring.datasource @ backend/src/main/resources/application.yml
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "shoppingList_local"
    command: postgres -c log_destination=stderr -c log_statement=all -c log_connections=on -c log_disconnections=on
