spring:
  profiles:
    active: local
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/shoppingList_local
    username: "admin"
    password: "admin"
  jackson:
    default-property-inclusion: non_null
  jpa:
    generate-ddl: true
    show-sql: false
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

logging:
  level:
    org:
      springframework:
        security: DEBUG
    root: info
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error

server:
  servlet:
    session:
      timeout: 82800s
    encoding:
      charset: utf-8
      force-response: true
