spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://aws-0-ap-northeast-1.pooler.supabase.com:6543/postgres
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jackson:
    default-property-inclusion: non_null
  jpa:
    generate-ddl: true
    show-sql: false
    hibernate:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

logging:
  level:
    org:
      springframework:
        security: DEBUG
    root: info
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error

server:
  servlet:
    session:
      timeout: 82800s
    encoding:
      charset: utf-8
      force-response: true
